# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Intro"
  pageRef = "intro"
  weight = 5

[[main]]
  name = "Posts"
  pageRef = "post"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "About"
  pageRef = "yaheya"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

# Social links in header
[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/yaheya"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/yaheya"
  weight = 110

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://linkedin.com/in/yaheya"
  weight = 120

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
