baseURL: ""
languageCode: en-us
title: Pulse
theme: PaperMod

params:
  homeInforParams:
    Title: "Hello Stranger"
    Content: "Welcome to my site!"
  socialIcons:
    - name: facebook
      url:  "https://facebook.com"


  cover:
    linkFullImages: true

ShowBreadCrumbs: true

ShowReadingTime: true

ShowShareButtons: true

ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url:  /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30